server {
    listen 80;

    location /projeto-korp {
        proxy_pass http://http-server-projeto-korp:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        return 404 "NGINX ativo, mas a rota nao foi encontrada.";
    }
}
